// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.69.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import "bridge_definitions.dart";
import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';

import 'dart:ffi' as ffi;

class RustImpl implements Rust {
  final RustPlatform _platform;
  factory RustImpl(ExternalLibrary dylib) => RustImpl.raw(RustPlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory RustImpl.wasm(FutureOr<WasmModule> module) =>
      RustImpl(module as ExternalLibrary);
  RustImpl.raw(this._platform);
  Future<KeyPair> createKeyPair({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_create_key_pair(port_),
      parseSuccessData: _wire2api_KeyPair,
      constMeta: kCreateKeyPairConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kCreateKeyPairConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "create_key_pair",
        argNames: [],
      );

  Future<String> getAddress({required KeyPair keyPair, dynamic hint}) {
    var arg0 = _platform.api2wire_KeyPair(keyPair);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_get_address(port_, arg0),
      parseSuccessData: _wire2api_String,
      constMeta: kGetAddressConstMeta,
      argValues: [keyPair],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kGetAddressConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "get_address",
        argNames: ["keyPair"],
      );

  DropFnType get dropOpaqueKeyPair => _platform.inner.drop_opaque_KeyPair;
  ShareFnType get shareOpaqueKeyPair => _platform.inner.share_opaque_KeyPair;
  OpaqueTypeFinalizer get KeyPairFinalizer => _platform.KeyPairFinalizer;

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  KeyPair _wire2api_KeyPair(dynamic raw) {
    return KeyPair.fromRaw(raw[0], raw[1], this);
  }

  String _wire2api_String(dynamic raw) {
    return raw as String;
  }

  int _wire2api_u8(dynamic raw) {
    return raw as int;
  }

  Uint8List _wire2api_uint_8_list(dynamic raw) {
    return raw as Uint8List;
  }
}

// Section: api2wire

// Section: finalizer

class RustPlatform extends FlutterRustBridgeBase<RustWire> {
  RustPlatform(ffi.DynamicLibrary dylib) : super(RustWire(dylib));

// Section: api2wire

  @protected
  wire_KeyPair api2wire_KeyPair(KeyPair raw) {
    final ptr = inner.new_KeyPair();
    _api_fill_to_wire_KeyPair(raw, ptr);
    return ptr;
  }
// Section: finalizer

  late final OpaqueTypeFinalizer _KeyPairFinalizer =
      OpaqueTypeFinalizer(inner._drop_opaque_KeyPairPtr);
  OpaqueTypeFinalizer get KeyPairFinalizer => _KeyPairFinalizer;
// Section: api_fill_to_wire

  void _api_fill_to_wire_KeyPair(KeyPair apiObj, wire_KeyPair wireObj) {
    wireObj.ptr = apiObj.shareOrMove();
  }
}

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.

/// generated by flutter_rust_bridge
class RustWire implements FlutterRustBridgeWireBase {
  @internal
  late final dartApi = DartApiDl(init_frb_dart_api_dl);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustWire(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustWire.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void store_dart_post_cobject(
    DartPostCObjectFnType ptr,
  ) {
    return _store_dart_post_cobject(
      ptr,
    );
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
          'store_dart_post_cobject');
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  Object get_dart_object(
    int ptr,
  ) {
    return _get_dart_object(
      ptr,
    );
  }

  late final _get_dart_objectPtr =
      _lookup<ffi.NativeFunction<ffi.Handle Function(ffi.UintPtr)>>(
          'get_dart_object');
  late final _get_dart_object =
      _get_dart_objectPtr.asFunction<Object Function(int)>();

  void drop_dart_object(
    int ptr,
  ) {
    return _drop_dart_object(
      ptr,
    );
  }

  late final _drop_dart_objectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.UintPtr)>>(
          'drop_dart_object');
  late final _drop_dart_object =
      _drop_dart_objectPtr.asFunction<void Function(int)>();

  int new_dart_opaque(
    Object handle,
  ) {
    return _new_dart_opaque(
      handle,
    );
  }

  late final _new_dart_opaquePtr =
      _lookup<ffi.NativeFunction<ffi.UintPtr Function(ffi.Handle)>>(
          'new_dart_opaque');
  late final _new_dart_opaque =
      _new_dart_opaquePtr.asFunction<int Function(Object)>();

  int init_frb_dart_api_dl(
    ffi.Pointer<ffi.Void> obj,
  ) {
    return _init_frb_dart_api_dl(
      obj,
    );
  }

  late final _init_frb_dart_api_dlPtr =
      _lookup<ffi.NativeFunction<ffi.IntPtr Function(ffi.Pointer<ffi.Void>)>>(
          'init_frb_dart_api_dl');
  late final _init_frb_dart_api_dl = _init_frb_dart_api_dlPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>)>();

  void wire_create_key_pair(
    int port_,
  ) {
    return _wire_create_key_pair(
      port_,
    );
  }

  late final _wire_create_key_pairPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_create_key_pair');
  late final _wire_create_key_pair =
      _wire_create_key_pairPtr.asFunction<void Function(int)>();

  void wire_get_address(
    int port_,
    wire_KeyPair key_pair,
  ) {
    return _wire_get_address(
      port_,
      key_pair,
    );
  }

  late final _wire_get_addressPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, wire_KeyPair)>>(
          'wire_get_address');
  late final _wire_get_address =
      _wire_get_addressPtr.asFunction<void Function(int, wire_KeyPair)>();

  wire_KeyPair new_KeyPair() {
    return _new_KeyPair();
  }

  late final _new_KeyPairPtr =
      _lookup<ffi.NativeFunction<wire_KeyPair Function()>>('new_KeyPair');
  late final _new_KeyPair =
      _new_KeyPairPtr.asFunction<wire_KeyPair Function()>();

  void drop_opaque_KeyPair(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _drop_opaque_KeyPair(
      ptr,
    );
  }

  late final _drop_opaque_KeyPairPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'drop_opaque_KeyPair');
  late final _drop_opaque_KeyPair = _drop_opaque_KeyPairPtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<ffi.Void> share_opaque_KeyPair(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _share_opaque_KeyPair(
      ptr,
    );
  }

  late final _share_opaque_KeyPairPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(
              ffi.Pointer<ffi.Void>)>>('share_opaque_KeyPair');
  late final _share_opaque_KeyPair = _share_opaque_KeyPairPtr
      .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();

  void free_WireSyncReturn(
    WireSyncReturn ptr,
  ) {
    return _free_WireSyncReturn(
      ptr,
    );
  }

  late final _free_WireSyncReturnPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(WireSyncReturn)>>(
          'free_WireSyncReturn');
  late final _free_WireSyncReturn =
      _free_WireSyncReturnPtr.asFunction<void Function(WireSyncReturn)>();
}

class _Dart_Handle extends ffi.Opaque {}

class wire_KeyPair extends ffi.Struct {
  external ffi.Pointer<ffi.Void> ptr;
}

typedef DartPostCObjectFnType = ffi.Pointer<
    ffi.NativeFunction<ffi.Bool Function(DartPort, ffi.Pointer<ffi.Void>)>>;
typedef DartPort = ffi.Int64;
