import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:xelis_mobile_wallet/shared/theme/more_colors.dart';

ThemeData lightTheme() {
  return FlexThemeData.light(
    extensions: <ThemeExtension<dynamic>>[
      const MoreColors(
        bgRadialColor1: Color.fromARGB(200, 255, 255, 255),
        bgRadialColor2: Color.fromARGB(178, 225, 225, 225),
        bgRadialColor3: Color.fromARGB(130, 150, 150, 150),
        bgRadialEndColor: Color.fromARGB(0, 255, 255, 255),
      )
    ],
    colors: const FlexSchemeColor(
      primary: Color.fromARGB(255, 50, 179, 146),
      primaryContainer: Color(0xffd0e4ff),
      secondary: Color(0xffac3306),
      secondaryContainer: Color(0xffffdbcf),
      tertiary: Color(0xff006875),
      tertiaryContainer: Color(0xff95f0ff),
      appBarColor: Color(0xffffdbcf),
      error: Color(0xffb00020),
    ),
    surfaceMode: FlexSurfaceMode.highBackgroundLowScaffold,
    blendLevel: 1,
    appBarStyle: FlexAppBarStyle.background,
    bottomAppBarElevation: 2.0,
    subThemesData: const FlexSubThemesData(
      blendOnLevel: 6,
      blendOnColors: false,
      useTextTheme: true,
      useM2StyleDividerInM3: true,
      adaptiveSplash: FlexAdaptive.all(),
      splashType: FlexSplashType.noSplash,
      splashTypeAdaptive: FlexSplashType.noSplash,
      adaptiveRemoveElevationTint: FlexAdaptive.excludeWebAndroidFuchsia(),
      adaptiveElevationShadowsBack: FlexAdaptive.excludeWebAndroidFuchsia(),
      adaptiveAppBarScrollUnderOff: FlexAdaptive.excludeWebAndroidFuchsia(),
      adaptiveRadius: FlexAdaptive.excludeWebAndroidFuchsia(),
      defaultRadiusAdaptive: 10.0,
      elevatedButtonSchemeColor: SchemeColor.onPrimaryContainer,
      elevatedButtonSecondarySchemeColor: SchemeColor.primaryContainer,
      outlinedButtonOutlineSchemeColor: SchemeColor.primary,
      toggleButtonsBorderSchemeColor: SchemeColor.primary,
      segmentedButtonSchemeColor: SchemeColor.primary,
      segmentedButtonBorderSchemeColor: SchemeColor.primary,
      unselectedToggleIsColored: true,
      sliderValueTinted: true,
      sliderTrackHeight: 3,
      inputDecoratorSchemeColor: SchemeColor.primary,
      inputDecoratorIsFilled: false,
      inputDecoratorBackgroundAlpha: 19,
      inputDecoratorRadius: 28.0,
      inputDecoratorFocusedBorderWidth: 1.0,
      inputDecoratorPrefixIconSchemeColor: SchemeColor.primary,
      fabUseShape: true,
      fabAlwaysCircular: true,
      fabSchemeColor: SchemeColor.tertiary,
      cardRadius: 8.0,
      popupMenuRadius: 6.0,
      popupMenuElevation: 3.0,
      dialogBackgroundSchemeColor: SchemeColor.surfaceVariant,
      dialogElevation: 1.0,
      dialogRadius: 8.0,
      adaptiveDialogRadius: FlexAdaptive.all(),
      snackBarRadius: 10,
      snackBarActionSchemeColor: SchemeColor.onPrimary,
      appBarScrolledUnderElevation: 1.0,
      drawerElevation: 1.0,
      drawerIndicatorSchemeColor: SchemeColor.primary,
      bottomSheetBackgroundColor: SchemeColor.surface,
      bottomSheetModalBackgroundColor: null,
      bottomSheetRadius: 18.0,
      bottomSheetModalElevation: 4.0,
      bottomNavigationBarMutedUnselectedLabel: false,
      bottomNavigationBarMutedUnselectedIcon: false,
      menuRadius: 6.0,
      menuElevation: 3.0,
      menuBarRadius: 0.0,
      menuBarElevation: 1.0,
      menuBarShadowColor: Color(0x00000000),
      navigationBarSelectedLabelSchemeColor: SchemeColor.primary,
      navigationBarMutedUnselectedLabel: false,
      navigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
      navigationBarMutedUnselectedIcon: false,
      navigationBarIndicatorSchemeColor: SchemeColor.primary,
      navigationBarIndicatorOpacity: 1.00,
      navigationBarElevation: 0.0,
      navigationRailSelectedLabelSchemeColor: SchemeColor.primary,
      navigationRailMutedUnselectedLabel: false,
      navigationRailSelectedIconSchemeColor: SchemeColor.onPrimary,
      navigationRailMutedUnselectedIcon: false,
      navigationRailIndicatorSchemeColor: SchemeColor.primary,
      navigationRailIndicatorOpacity: 1.00,
      navigationRailBackgroundSchemeColor: SchemeColor.surface,
    ),
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    useMaterial3: true,
    fontFamily: GoogleFonts.notoSansDisplay().fontFamily,
  );
}

ThemeData darkTheme() {
  return FlexThemeData.dark(
    extensions: <ThemeExtension<dynamic>>[
      const MoreColors(
        bgRadialColor1: Color.fromARGB(153, 75, 75, 75),
        bgRadialColor2: Color.fromARGB(178, 100, 100, 100),
        bgRadialColor3: Color.fromARGB(153, 25, 25, 25),
        bgRadialEndColor: Color.fromARGB(0, 0, 0, 0),
      )
    ],
    colors: const FlexSchemeColor(
      primary: Color(0xff02ffcf),
      primaryContainer: Color(0xff57859d),
      secondary: Color(0xffffb59d),
      secondaryContainer: Color(0xff872100),
      tertiary: Color(0xff86d2e1),
      tertiaryContainer: Color(0xff004e59),
      appBarColor: Color(0xff872100),
      error: Color(0xffcf6679),
    ),
    onPrimary: Colors.white,
    surfaceMode: FlexSurfaceMode.highScaffoldLowSurface,
    blendLevel: 2,
    appBarStyle: FlexAppBarStyle.background,
    bottomAppBarElevation: 2.0,
    subThemesData: const FlexSubThemesData(
      blendOnLevel: 8,
      useTextTheme: true,
      useM2StyleDividerInM3: true,
      adaptiveSplash: FlexAdaptive.all(),
      splashType: FlexSplashType.noSplash,
      splashTypeAdaptive: FlexSplashType.noSplash,
      adaptiveElevationShadowsBack: FlexAdaptive.all(),
      adaptiveAppBarScrollUnderOff: FlexAdaptive.excludeWebAndroidFuchsia(),
      adaptiveRadius: FlexAdaptive.excludeWebAndroidFuchsia(),
      defaultRadiusAdaptive: 10.0,
      elevatedButtonSchemeColor: SchemeColor.onPrimaryContainer,
      elevatedButtonSecondarySchemeColor: SchemeColor.primaryContainer,
      outlinedButtonOutlineSchemeColor: SchemeColor.primary,
      toggleButtonsBorderSchemeColor: SchemeColor.primary,
      segmentedButtonSchemeColor: SchemeColor.primary,
      segmentedButtonBorderSchemeColor: SchemeColor.primary,
      unselectedToggleIsColored: true,
      sliderValueTinted: true,
      sliderTrackHeight: 3,
      inputDecoratorSchemeColor: SchemeColor.primary,
      inputDecoratorIsFilled: false,
      inputDecoratorBackgroundAlpha: 22,
      inputDecoratorRadius: 28.0,
      inputDecoratorFocusedBorderWidth: 1.0,
      inputDecoratorPrefixIconSchemeColor: SchemeColor.primary,
      fabUseShape: true,
      fabAlwaysCircular: true,
      fabSchemeColor: SchemeColor.tertiary,
      cardRadius: 8.0,
      popupMenuRadius: 6.0,
      popupMenuElevation: 3.0,
      dialogBackgroundSchemeColor: SchemeColor.surfaceVariant,
      dialogElevation: 1.0,
      dialogRadius: 8.0,
      adaptiveDialogRadius: FlexAdaptive.all(),
      snackBarRadius: 10,
      snackBarActionSchemeColor: SchemeColor.onPrimary,
      appBarScrolledUnderElevation: 3.0,
      drawerElevation: 1.0,
      drawerIndicatorSchemeColor: SchemeColor.primary,
      bottomSheetBackgroundColor: SchemeColor.surface,
      bottomSheetModalBackgroundColor: null,
      bottomSheetRadius: 18.0,
      bottomSheetModalElevation: 4.0,
      bottomNavigationBarMutedUnselectedLabel: false,
      bottomNavigationBarMutedUnselectedIcon: false,
      menuRadius: 6.0,
      menuElevation: 3.0,
      menuBarRadius: 0.0,
      menuBarElevation: 1.0,
      menuBarShadowColor: Color(0x00000000),
      navigationBarSelectedLabelSchemeColor: SchemeColor.primary,
      navigationBarMutedUnselectedLabel: false,
      navigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
      navigationBarMutedUnselectedIcon: false,
      navigationBarIndicatorSchemeColor: SchemeColor.primary,
      navigationBarIndicatorOpacity: 1.00,
      navigationBarElevation: 0.0,
      navigationRailSelectedLabelSchemeColor: SchemeColor.primary,
      navigationRailMutedUnselectedLabel: false,
      navigationRailSelectedIconSchemeColor: SchemeColor.onPrimary,
      navigationRailMutedUnselectedIcon: false,
      navigationRailIndicatorSchemeColor: SchemeColor.primary,
      navigationRailIndicatorOpacity: 1.00,
      navigationRailBackgroundSchemeColor: SchemeColor.surface,
    ),
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    useMaterial3: true,
    fontFamily: GoogleFonts.notoSansDisplay().fontFamily,
  );
}

ThemeData xelisTheme() {
  return FlexThemeData.dark(
    extensions: <ThemeExtension<dynamic>>[
      const MoreColors(
        bgRadialColor1: Color.fromARGB(153, 0, 170, 129),
        bgRadialColor2: Color.fromARGB(178, 5, 124, 132),
        bgRadialColor3: Color.fromARGB(153, 0, 170, 150),
        bgRadialEndColor: Color.fromARGB(0, 0, 0, 0),
      )
    ],
    colors: const FlexSchemeColor(
      primary: Color(0xFF02FFCF),
      primaryContainer: Color(0xff57859d),
      secondary: Color(0xffffb59d),
      secondaryContainer: Color(0xff872100),
      tertiary: Color(0xff86d2e1),
      tertiaryContainer: Color(0xff004e59),
      appBarColor: Color(0xff872100),
      error: Color.fromARGB(255, 219, 26, 61),
    ),
    onPrimary: const Color.fromARGB(210, 0, 0, 0),
    surfaceMode: FlexSurfaceMode.highScaffoldLowSurface,
    blendLevel: 2,
    appBarStyle: FlexAppBarStyle.background,
    bottomAppBarElevation: 2.0,
    subThemesData: const FlexSubThemesData(
      thinBorderWidth: 1,
      blendOnLevel: 8,
      useTextTheme: true,
      useM2StyleDividerInM3: true,
      adaptiveSplash: FlexAdaptive.all(),
      splashType: FlexSplashType.noSplash,
      splashTypeAdaptive: FlexSplashType.noSplash,
      adaptiveElevationShadowsBack: FlexAdaptive.all(),
      adaptiveAppBarScrollUnderOff: FlexAdaptive.excludeWebAndroidFuchsia(),
      adaptiveRadius: FlexAdaptive.excludeWebAndroidFuchsia(),
      defaultRadiusAdaptive: 10.0,
      elevatedButtonSchemeColor: SchemeColor.onPrimaryContainer,
      elevatedButtonSecondarySchemeColor: SchemeColor.primaryContainer,
      outlinedButtonOutlineSchemeColor: SchemeColor.primary,
      toggleButtonsBorderSchemeColor: SchemeColor.primary,
      segmentedButtonSchemeColor: SchemeColor.primary,
      segmentedButtonBorderSchemeColor: SchemeColor.primary,
      unselectedToggleIsColored: true,
      sliderValueTinted: true,
      sliderTrackHeight: 3,
      inputDecoratorSchemeColor: SchemeColor.primary,
      inputDecoratorIsFilled: false,
      inputDecoratorBackgroundAlpha: 22,
      inputDecoratorRadius: 15,
      inputDecoratorBorderType: FlexInputBorderType.underline,
      //inputDecoratorFocusedBorderWidth: 1.0,
      inputDecoratorPrefixIconSchemeColor: SchemeColor.primary,
      fabUseShape: true,
      fabAlwaysCircular: true,
      fabSchemeColor: SchemeColor.tertiary,
      cardRadius: 8.0,
      popupMenuRadius: 6.0,
      popupMenuElevation: 3.0,
      dialogBackgroundSchemeColor: SchemeColor.surfaceVariant,
      dialogElevation: 1.0,
      dialogRadius: 8.0,
      adaptiveDialogRadius: FlexAdaptive.all(),
      snackBarRadius: 10,
      snackBarActionSchemeColor: SchemeColor.onPrimary,
      appBarScrolledUnderElevation: 3.0,
      drawerElevation: 1.0,
      drawerIndicatorSchemeColor: SchemeColor.primary,
      bottomSheetBackgroundColor: SchemeColor.surface,
      bottomSheetModalBackgroundColor: null,
      bottomSheetRadius: 18.0,
      bottomSheetModalElevation: 4.0,
      bottomNavigationBarMutedUnselectedLabel: false,
      bottomNavigationBarMutedUnselectedIcon: false,
      menuRadius: 6.0,
      menuElevation: 3.0,
      menuBarRadius: 0.0,
      menuBarElevation: 1.0,
      menuBarShadowColor: Color(0x00000000),
      navigationBarSelectedLabelSchemeColor: SchemeColor.primary,
      navigationBarMutedUnselectedLabel: false,
      navigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
      navigationBarMutedUnselectedIcon: false,
      navigationBarIndicatorSchemeColor: SchemeColor.primary,
      navigationBarIndicatorOpacity: 1.00,
      navigationBarElevation: 0.0,
      navigationRailSelectedLabelSchemeColor: SchemeColor.primary,
      navigationRailMutedUnselectedLabel: false,
      navigationRailSelectedIconSchemeColor: SchemeColor.onPrimary,
      navigationRailMutedUnselectedIcon: false,
      navigationRailIndicatorSchemeColor: SchemeColor.primary,
      navigationRailIndicatorOpacity: 1.00,
      navigationRailBackgroundSchemeColor: SchemeColor.surface,
    ),
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    useMaterial3: true,
    fontFamily: GoogleFonts.notoSansDisplay().fontFamily,
  );
}
