import 'package:flutter/services.dart';
import 'package:forui/forui.dart';
import 'package:flutter/material.dart';
import 'package:genesix/shared/theme/dialog_style.dart';
import 'package:genesix/shared/theme/text_field_style.dart';

// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified function and pass it to [FTheme].
///
/// You can also generate styles to be used in the generated [FThemeData] using:
/// ```shell
/// dart forui style create [styles]
/// ```
///
/// See https://forui.dev/docs/themes#customize-themes for more information.
FThemeData get greenLight {
  const colors = FColors(
    brightness: Brightness.light,
    systemOverlayStyle: SystemUiOverlayStyle.dark,
    barrier: Color(0x33000000),
    background: Color(0xFFFFFFFF),
    foreground: Color(0xFF030712),
    primary: Color(0xFF1AE3C2),
    primaryForeground: Color(0xFFF9FAFB),
    secondary: Color(0xFFF3F4F6),
    secondaryForeground: Color(0xFF111827),
    muted: Color(0xFFF3F4F6),
    mutedForeground: Color(0xFF6B7280),
    destructive: Color(0xFFEF4444),
    destructiveForeground: Color(0xFFF9FAFB),
    error: Color(0xFFEF4444),
    errorForeground: Color(0xFFF9FAFB),
    border: Color(0xFFE5E7EB),
    card: Color(0xFFFFFFFF),
  );

  final typography = _typography(colors: colors);
  final style = _style(colors: colors, typography: typography);

  return FThemeData(
    colors: colors,
    typography: typography,
    style: style,
    dialogStyle: dialogStyle(
      style: style,
      colors: colors,
      typography: typography,
    ),
    textFieldStyle: textFieldStyle(
      colors: colors,
      typography: typography,
      style: style,
    ),
  );
}

FThemeData get greenDark {
  const colors = FColors(
    brightness: Brightness.dark,
    systemOverlayStyle: SystemUiOverlayStyle.light,
    barrier: Color(0x7A000000),
    background: Color(0xFF030712),
    foreground: Color(0xFFF9FAFB),
    primary: Color(0xFF15BFAE),
    // primary: Color(0xFF11F3D1),
    // primary: Color(0xFF19EDD0),
    primaryForeground: Color(0xFFF9FAFB),
    secondary: Color(0xFF1F2937),
    secondaryForeground: Color(0xFFF9FAFB),
    muted: Color(0xFF1F2937),
    mutedForeground: Color(0xFF9CA3AF),
    destructive: Color(0xFF7F1D1D),
    destructiveForeground: Color(0xFFF9FAFB),
    error: Color(0xFF7F1D1D),
    errorForeground: Color(0xFFF9FAFB),
    border: Color(0xFF1F2937),
    card: Color(0xFF030712),
  );

  final typography = _typography(colors: colors);
  final style = _style(colors: colors, typography: typography);

  return FThemeData(
    colors: colors,
    typography: typography,
    style: style,
    dialogStyle: dialogStyle(
      style: style,
      colors: colors,
      typography: typography,
    ),
    textFieldStyle: textFieldStyle(
      colors: colors,
      typography: typography,
      style: style,
    ),
  );
}

FTypography _typography({
  required FColors colors,
  String defaultFontFamily = 'packages/forui/Inter',
}) => FTypography(
  xs: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 12,
    height: 1,
  ),
  sm: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 14,
    height: 1.25,
  ),
  base: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 16,
    height: 1.5,
  ),
  lg: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 18,
    height: 1.75,
  ),
  xl: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 20,
    height: 1.75,
  ),
  xl2: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 22,
    height: 2,
  ),
  xl3: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 30,
    height: 2.25,
  ),
  xl4: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 36,
    height: 2.5,
  ),
  xl5: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 48,
    height: 1,
  ),
  xl6: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 60,
    height: 1,
  ),
  xl7: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 72,
    height: 1,
  ),
  xl8: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 96,
    height: 1,
  ),
);

FStyle _style({required FColors colors, required FTypography typography}) =>
    FStyle(
      formFieldStyle: FFormFieldStyle.inherit(
        colors: colors,
        typography: typography,
      ),
      focusedOutlineStyle: FFocusedOutlineStyle(
        color: colors.primary,
        borderRadius: const BorderRadius.all(Radius.circular(8)),
      ),
      iconStyle: IconThemeData(color: colors.primary, size: 20),
      tappableStyle: FTappableStyle(),
      borderRadius: const FLerpBorderRadius.all(Radius.circular(8), min: 24),
      borderWidth: 1,
      pagePadding: const EdgeInsets.symmetric(vertical: 8, horizontal: 12),
      shadow: const [
        BoxShadow(
          color: Color(0x0d000000),
          offset: Offset(0, 1),
          blurRadius: 2,
        ),
      ],
    );
